@WssDashApi_HostAddress = http://localhost:5207

GET {{WssDashApi_HostAddress}}/api/health
Accept: application/json

###

GET {{WssDashApi_HostAddress}}/weatherforecast/
Accept: application/json

###
